# SITE SETTINGS
title: TDWG
repository: tdwg/website

# SOCIAL PROFILES
social:
  email: secretary@tdwg.org
  bluesky: tdwg.org
  linkedin: https://www.linkedin.com/company/tdwg/
  facebook: https://www.facebook.com/groups/326780777736/
  github: tdwg

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
posts_on_home: false
tweets_on_home: false
archive_permalink: /news/
github_edit: master
logo: /assets/theme/images/tdwg-logo-long.svg

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/news/:year/:slug/" # Use /news/yyyy/{filename}/ as permalink for all posts
      toc: false
  - scope:
      path: conferences/2020
    values:
      navigation: tdwg-2020-navigation
  - scope:
      path: conferences/2021
    values:
      navigation: tdwg-2021-navigation
  - scope:
      path: conferences/2022
    values:
      navigation: tdwg-2022-navigation
  - scope:
      path: conferences/2023
    values:
      navigation: tdwg-2023-navigation
  - scope:
      path: conferences/2024
    values:
      navigation: tdwg-2024-navigation
  - scope:
      path: conferences/2025
    values:
      navigation: tdwg-2025-navigation
